# Generated by Django 4.1.5 on 2023-04-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
