# Generated by Django 4.1.5 on 2023-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='continuation_of_content',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ilustration',
            field=models.ImageField(null=True, upload_to='blog/images/blog'),
        ),
    ]
