# Generated by Django 4.1.5 on 2023-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_of_content',
            field=models.TextField(max_length=6000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ilustration_2',
            field=models.ImageField(null=True, upload_to='blog/images/blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='continuation_of_content',
            field=models.TextField(max_length=6000, null=True),
        ),
    ]
